AllCops:
  NewCops: enable

Style/FormatStringToken:
  Description: 'Use a consistent style for format string tokens.'
  Enabled: false

Style/CommandLiteral:
  Description: 'Use `` or %x around command literals.'
  Enabled: false

Style/PerlBackrefs:
  Description: 'Avoid Perl-style regex back references.'
  Enabled: false

Metrics/MethodLength:
  Enabled: true
  CountComments: false  # count full line comments?
  CountAsOne: ['array', 'hash', 'heredoc']
  Max: 15

Style/RedundantReturn:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false
